# (from: https://hub.docker.com/_/wordpress/)
version: '3.1'

services:

  wordpress:
    image: wordpress:4.9.7
    restart: always
    ports:
      - 8080:80
    volumes:
     - ./docker_volumes/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker_volumes/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      